<?php

return [
	'groups' => [
		'validacion' => ['validacion.*'],
		'catProveedor' => ['cat_proveedor.*'],
		'proveedor' => ['proveedor.*'],
		'adjudicacion' => ['adjudicacion.*'],
		'anexosAdjudicacion' => ['anexos_adjudicacion.*'],
		'urg' => ['urg.*'],
		'invitacion' => ['invitacion.*'],
		'anexosInvitacion' => ['anexos_invitacion.*'],
		'licitacion' => ['licitacion.*'],
		'anexosLicitacion' => ['anexos_licitacion.*'],
		'contratosMarco' => ['contrato.*'],
		'anexosContrato' => ['anexos_contrato.*'],
		'expedientesContrato' => ['expedientes_contrato.*'],
		'catProducto' => ['cat_producto.*'],
		'service' => ['service.*'],
		'grupoRevisor' => ['grupo_revisor.*'],
		'contratoMarcoUrg' => ['cm_urg.*'],
		'proveedorFichaProducto' => ['proveedor_fp.*'],
		'habilitarProveedor' => ['habilitar_proveedores.*'],
		'habilitarProductos' => ['habilitar_productos.*'],
		'submenu' => ['submenu.*'],
		'tiendaUrg' => ['tienda_urg.*'],
		'productosPreguntasRespuestas' => ['pro_pre.*'],
		'validacionAdministrativas' => ['validacion_administrativas.*'],
		'validadorTecnico' => ['validador_tecnico.*'],
		'usuarios' => ['usuarios.*'],
		'requisiciones' => ['requisiciones.*'],
		'bienServicio' => ['bien_servicio.*'],
		'carritoCompra' => ['carrito_compra.*'],
		'pfu' => ['pfu.*'],
		'ocp' => ['orden_compra_proveedores.*'],
		'ordenCompra' => ['orden_compra.*'],
		'solicitudCompra' => ['solucitud_compra.*'],
		'ordenCompraUrg' => ['orden_compra_urg.*'],
		'ordenCompraEnvio' => ['orden_compra_envio.*'],
		'ordenCompraProrroga' => ['orden_compra_prorroga.*'],
		'ordenCompraSustitucion' => ['orden_compra_sustitucion.*'],
		'ordenCompraFactura' => ['orden_compra_factura.*'],
		'firmante' => ['firmante.*'],
		'ordenCompraPago' => ['orden_compra_pago.*'],
		'proveedorComentario' => ['proveedor_comentario.*'],
		'reporteProveedor' => ['reporte_proveedor.*'],
		'incidenciaProveedor' => ['incidencia_proveedor.*'],
		'ordenCompraAdmin' => ['orden_compra_admin.*'],
		'admin' => ['admin.*'],
		'mensajeUser' => ['mensajes_urg.*'],
		'incidenciaUrg' => ['incidencia_urg.*'],
		'reporteAdmin' => ['reporte_admin.*'],
		'reporteUrg' => ['reporte_urg.*'],
    	'mensajeProveedor' => ['mensaje_proveedor.*'],
    	'contratoOcUrg' => ['contrato_oc_urg.*'],
    	'productoAdmin' => ['producto_admin.*'],
	],
];
